application: imbaxangular
version: 1
runtime: php
api_version: 1
threadsafe: true

handlers:
- url: /
  script: app/index.html

- url: /css
  static_dir: app/css

- url: /js
  static_dir: app/js

- url: /templates
  static_dir: app/templates

- url: /directives
  static_dir: app/directives

- url: /resources/product.php
  script: app/resources/product.php
